### ISSUE TITLE
Home of this code in IRODS 

### ISSUE THREAD

**Issue by clarisca** [heliumdatacommons/irods_resource_plugin_globus#1]
@jasoncoposky : I assume that this code will be homed in iRODS repos. Is that correct?

**Comment by theferrit32** [comment]
If this is referring to an OpenID Connect plugin, the development of that code is currently living in irods-contrib:

https://github.com/irods-contrib/irods_auth_plugin_openid

**Comment by clarisca** [comment]
@theferrit32 : this is referring to a plugin for Globus connect --which will likely live in irods-contrib repo above.

**Comment by theferrit32** [comment]
for now I will just maintain the code in this repository, but can move it into a new repository in irods-contrib if that is desired
